development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
test:
  secret_key_base: <%= ENV["TEST_SECRET_KEY_BASE"] %>
  codeclimate_repo_token: <%= ENV["CODECLIMATE_REPO_TOKEN"] %>
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
